@startuml
actor       Mahasiswa       as mhs
actor       Dosen       as dosen
'participant FE.BE.DB as mid
participant PerkuliahanContract as perkuliahan
database    Blockchain      as bc
entity      Mahasiswa      as mhsState
entity      Dosen      as dosenState
entity      Perkuliahan      as perkuliahanState
entity      KRS      as krs
entity      KHS      as khs

mhs -> perkuliahan : ajukanKrs()
activate perkuliahan

perkuliahan -> bc : getMahasiswa
bc -> mhsState
bc -> perkuliahan
perkuliahan -> perkuliahan : verifikasiMahasiswa

perkuliahan -> bc : getPerkuliahan
bc -> perkuliahanState
bc -> perkuliahan
perkuliahan -> perkuliahan : verifikasiPerkuliahan

perkuliahan -> bc : writeKrs
bc -> krs
perkuliahan -> mhs
deactivate perkuliahan
'============================================
dosen -> perkuliahan : setujuiKrs()
activate perkuliahan

perkuliahan -> bc : getDosen
bc -> dosenState
bc -> perkuliahan
perkuliahan -> perkuliahan : verifikasiDosen

perkuliahan -> bc : getKrs
bc -> krs
bc -> perkuliahan

perkuliahan -> bc : writeKrs
bc -> krs

perkuliahan -> bc : writeKhs
bc -> khs

perkuliahan -> dosen
deactivate perkuliahan

'============================================
dosen -> perkuliahan : nilaiPerkuliahan()
activate perkuliahan

perkuliahan -> bc : getKhs
bc -> khs
bc -> perkuliahan

perkuliahan -> perkuliahan : verifikasiTanggalPengisian

perkuliahan -> bc : getDosen
bc -> dosenState
bc -> perkuliahan
perkuliahan -> perkuliahan : verifikasiDosen

perkuliahan -> bc : writeKhs
bc -> khs

perkuliahan -> dosen
deactivate perkuliahan

@enduml